### ISSUE TITLE
Create a Colab notebook for cloning and sharing

### ISSUE THREAD

**Issue by charlie-sanders** [PRQL/pyprql#57]

**Comment by max-sixty** [comment]
This would be great, and could even be self-documenting — so I can't screw up the docs! https://github.com/prql/PyPrql/pull/58

**Comment by charlie-sanders** [comment]
https://colab.research.google.com/drive/1FLxPgHjlCGqgDHuMds6l3ThynYGOL-Zy#scrollTo=Yn7er5MORy5l , @max-sixty  could you look over when you get a chance, then I'll put in the docs

**Comment by max-sixty** [comment]
Very cool @charlie-sanders !

If you want a quick dump of ideas:
- I see what you mean about the syntax highlighting! It's worse in Colab than Jupyter because of all the false positive spellchecks
- Would be nice in a future version to show the pandas integration; e.g. pulling `df` out
- I don't think we need the `"Returning data to _" statement`, that's a default in IPython kernels (same with `Done` probably, maybe we soup it up with tqdm for expensive queries though)
- Would be nice to show the elegant df representation rather than the terminal-based one, probably requires calling `_repr_html` in the magic. here's the difference.
<img width="385" alt="image" src="https://user-images.githubusercontent.com/5635139/176320703-f546e495-c246-4671-93c8-e2ba3ed0d232.png">

**Comment by max-sixty** [comment]
Done in https://github.com/PRQL/pyprql/pull/113
